---
name: Linux Build

on:
  push:

jobs:
  build:
    name: "Python ${{ matrix.python-version }}-${{ matrix.platform }}-wx-${{ matrix.wx-version }}"
    runs-on: ${{ matrix.platform }}
    env:
      USING_COVERAGE: '3.6,3.7,3.8,3.9'

    strategy:
      fail-fast: False
      matrix:
        python-version:
         - "3.6"
         - "3.7"
         - "3.8"
         - "3.9"
        platform:
         - "ubuntu-16.04"
         - "ubuntu-18.04"
         - "ubuntu-20.04"
        wx-version:
         - "4.0.7.post2"
         - "4.1.0"
         - "4.1.1"

    steps:

      - name: Setup Python ðŸ
        uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Install dependencies ðŸ”§
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip
          python -m pip install "setuptools==46.1.0" "wheel>=0.36.2"
          sudo apt install libgtk-3-dev libwebkit2gtk-4.0-dev libglu1-mesa-dev

      - name: "Build Wheel"
        run: "python -m pip wheel --no-deps wxPython==${{ matrix.wx-version }} --wheel-dir ./wheels --verbose"

      - name: "Upload Artefacts"
        uses: actions/upload-artifact@v2
        with:
          name: "wxPython-${{ matrix.wx-version }}-py${{ matrix.python-version }}-${{ matrix.platform }}"
          path: ./wheels/*.whl
